#define _WINSOCKAPI_
#include <winsock2.h>
#include <windows.h>

#include <K2DCollider.cpp>
#include <K2DColliderManager.cpp>
#include <KActor.cpp>
#include <KAlphaRender.cpp>
#include <KBitMap.cpp>
#include <KBitMapAnimator.cpp>
#include <KBitMapRender.cpp>
#include <KComponent.cpp>
#include <KConsoleRender.cpp>
#include <KCore.cpp>
#include <KCore_Pointer.cpp>
#include <KDebugManager.cpp>
#include <KInputManager.cpp>
#include <KName.cpp>
#include <KOne.cpp>
#include <KRectCollision.cpp>
#include <KRenderManager.cpp>
#include <KRenderer.cpp>
#include <KScene.cpp>
#include <KSceneManager.cpp>
#include <KSpriteAnimator.cpp>
#include <KSpriteRender.cpp>
#include <KTextRender.cpp>
#include <KTimeManager.cpp>
#include <KTransform.cpp>
#include <KUIClicker.cpp>
#include <KVector.cpp>
#include <KWindow.cpp>
#include <KWindowManager.cpp>
